# Makefile.osx  : makefile for gamelib

libs = \
 gl.so \
 glfw.so \
 sys.so 

all:
	cd ../gl && $(MAKE) -f Makefile.osx
	cp ../gl/gl.so .
	cd ../glfw && $(MAKE) -f Makefile.osx
	cp ../glfw/lua_glfw.so .
	cd ../util && $(MAKE) -f Makefile.osx
	cp ../util/sys.so .

clean:
	-rm -rf $(libs)
	cd ../gl && $(MAKE) -f Makefile.osx clean
	cd ../glfw && $(MAKE) -f Makefile.osx clean
	cd ../util && $(MAKE) -f Makefile.osx clean
