  {"init", lw_init},
  {"cleanup", lw_cleanup},
  {"num_rows", lw_num_rows},
  {"num_cols", lw_num_cols},
  {"char_width", lw_char_width},
  {"char_height", lw_char_height},
  {"set_text_buf", lw_set_text_buf},
  {"draw_text_buf", lw_draw_text_buf},
