# mingw Makefile for gl lua wrapper

lua_dir = ../lua
glfw_dir = ../glfw/libglfw

CC=gcc
CFLAGS += -O0 -g -Wall
SO=dll
lua_libs=$(lua_dir)/lua51.dll

includes= \
 -I$(glfw_dir)/include \
 -I$(lua_dir)/include
 
all: lua_gl.$(SO)

lua_gl.$(SO): lua_gl.o
	$(CC) -o $@ -shared $< $(lua_libs) -lopengl32 -glu32

lua_gl.o: constant_defs.c lua_gl_func_def.c lua_gl_func_reg.c lua_gl.c 
	$(CC) -o $@ $(CFLAGS) $(includes) -c lua_gl.c

clean:
	rm -f *.o *.$(SO)


