return {
  ['glBegin']=true,
  ['glBlendFunc']=true,
  ['glClear']=true,
  ['glClearColor']=true,
  ['glColor3f']=true,
  ['glColor4f']=true,
  ['glEnd']=true,
  ['glFrustum']=true,
  ['glLoadIdentity']=true,
  ['glMatrixMode']=true,
  ['glOrtho']=true,
  ['glTranslatef']=true,
  ['glVertex2f']=true,
  ['glVertex3f']=true,
}
