# Makefile for gl lua wrapper

lua_dir = ../lua
glfw_dir = ../glfw/libglfw

CC=gcc
CFLAGS += -O0 -g -Wall

includes= \
 -I$(glfw_dir)/include \
 -I$(lua_dir)/include
 
all: lua_gl.so

lua_gl.so: lua_gl.o
	$(CC) -o $@ -dynamiclib -undefined dynamic_lookup $< -framework Cocoa -framework OpenGL

lua_gl.o: constant_defs.c lua_gl_func_def.c lua_gl_func_reg.c lua_gl.c 
	$(CC) -o $@ $(CFLAGS) $(includes) -c lua_gl.c

clean:
	rm -f *.o *.so
