# OSX Makefile for img lib

CC = gcc
CFLAGS += -g -Wall

all: img.so 

img.so: img.o
	$(CC) -o $@ -dynamiclib -undefined dynamic_lookup img.o libpng/libpng.so

img.o: img.c
	$(CC) -o $@ $(CFLAGS) -I libpng/include -c $<

clean:
	-rm *.o *.so
