# Makefile.osx: Mac OSX makefile for img lib

CC=gcc
CFLAGS+=-g -Wall -Izlib -Ilibpng/include 
SO=so

all: subdirs img.$(SO)

img.$(SO): img.o
	$(CC) -o $@ -dynamiclib -undefined dynamic_lookup img.o libpng/libpng.$(SO)
	install_name_tool -change libpng.$(SO) @executable_path/libpng.$(SO) $@

img.o: img.c
	$(CC) -o $@ $(CFLAGS) -c $<

clean: subdirs
	-rm *.o *.$(SO)

subdirs:
	cd zlib && make -f Makefile.osx $(MAKECMDGOALS)
	cd libpng && make -f Makefile.osx $(MAKECMDGOALS)
